on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: "Login via Azure CLI"
        uses: azure/docker-login@v1
        with:
          login-server: rsenumistral.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: "Build and push docker image"
        run: |
          docker build . -t rsenumistral.azurecr.io/open-udm:${{ github.sha }}
          docker push rsenumistral.azurecr.io/open-udm:${{ github.sha }}