name: build

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install swig (windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install swig -y

    - name: Build and install openudm
      run: |
        python setup.py build
        python setup.py develop

    - name: Run script
      run: |
        python -m openudm
        raster_to_vector -i Data/out_cell_dev.asc -o Data/buildings.gpkg -c 22

