name: build

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}

    - name: Setup Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: udm
        environment-file: environment.yml
        use-only-tar-bz2: true

    - name: Build openudm
      run: |
        python setup.py build
        python setup.py develop
      shell: bash -l {0}

    - name: Run script to test UDM
      run: |
        python -m openudm
      shell: bash -l {0}

    - name: Run UFG tool
      run: |
        generate_urban_fabric -i Tiles
      shell: bash -l {0}

    - name: Run test for R2V tool
      run: |
        raster_to_vector -i Tiles/out_uf.asc -o Data/new_buildings.gpkg -f buildings
      shell: bash -l {0}