name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py build
        python setup.py sdist
        pip install twine
        twine upload dist/*
