name: Test

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: goanpeca/setup-miniconda@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install swig
      run: conda install swig
      shell: bash -l {0}
    - name: Build and install openudm
      run: |
        python setup.py build
        python setup.py install
      shell: bash -l {0}
    - name: Run script
      run: |
        python scripts/udm_solo.py
      shell: bash -l {0}
